# Generated by Django 5.2.16 on 2026-07-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
        migrations.RemoveField(
            model_name='cars',
            name='is_available',
        ),
    ]
